name: Firebase App Distribution release

on:
  push:
    branches: [main]

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create Google Play Service Account JSON file
        run: echo '${{ secrets.FIREBASE_GOOGLE_SERVICE_JSON }}' | base64 -d > app/google-services.json

      - name: Run unit tests
        run: ./gradlew clean test

  build-and-deploy-to-firebase:
    name: Build and Firebase Distribution
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create Google Play Service Account JSON file
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' | base64 -d > app/google-services.json

      - name: Create release directory
        run: mkdir -p app/release

      - name: Generate version name
        id: version
        run: |
          # Get the current year and month in YY.MM format
          YEAR_MONTH=$(date +'%y.%m')
          
          # Count number of tags that start with the current YY.MM
          TAG_COUNT=$(git tag -l "$YEAR_MONTH.*" | wc -l)
          # Increment tag count by 1 (or set to 1 if no matching tags exist)
          TAG_VERSION=$((TAG_COUNT + 1))
          
          # Create version name in format YY.MM.TAG.VERSION_CODE
          VERSION_NAME="${YEAR_MONTH}.${TAG_VERSION}.${{ github.run_number }}"
          
          echo "year_month=$YEAR_MONTH" >> $GITHUB_OUTPUT
          echo "tag_version=$TAG_VERSION" >> $GITHUB_OUTPUT
          echo "version_name=$VERSION_NAME" >> $GITHUB_OUTPUT
          echo "Version name: $VERSION_NAME"

      - name: Version Bump
        uses: chkfung/android-version-actions@v1.2.3
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{ github.run_number }}
          versionName: ${{ steps.version.outputs.version_name }}

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Build Release Application (APK)
        run: ./gradlew assembleRelease

      - name: Copy APK to release directory
        run: cp app/build/outputs/apk/release/*.apk app/release/app-release.apk

      - name: Install Android Build Tools 29.0.3
        run: sdkmanager "build-tools;29.0.3"

      - name: Sign Android Release (APK)
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEYSTORE }}
          alias: ${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_SIGNING_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_SIGNING_KEY_ALIAS_PASSWORD }}

      - name: Debug Release Files
        run: |
          echo "SIGNED_RELEASE_FILE: ${{ env.SIGNED_RELEASE_FILE }}"
          echo "Files in app/release:"
          ls -la app/release/
          echo "Files in app directory:"
          ls -la app/

      - name: Copy signed apk and abb to release directory
        run: |
          cp app/release/app-release-signed.apk app/release/app-firebase-release.apk

      - name: Google FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY Decoding
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY }}' | base64 -d > app/uttarauniversityerp_firebase_service_account_key.json

      - name: Read Firebase service account JSON content
        id: read_firebase_json
        run: |
          echo "json<<EOF" >> $GITHUB_OUTPUT
          cat app/uttarauniversityerp_firebase_service_account_key.json >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Upload Artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ steps.read_firebase_json.outputs.json }}
          groups: toufikforyou
          file: app/release/app-firebase-release.apk