name: Pull Request Checks Unit Tests

on:
  pull_request:
    branches: [main]

jobs:
  verify:
    name: Verify Build & Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create Google Play Service Account JSON file
        run: echo '${{ secrets.FIREBASE_GOOGLE_SERVICE_JSON }}' | base64 -d > app/google-services.json

      - name: Run unit tests
        run: ./gradlew clean test

      - name: Verify debug build
        run: ./gradlew assembleDebug

      - name: Verify release build
        run: ./gradlew bundleRelease